# Generated by Django 5.1.4 on 2025-01-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('alt_text', models.CharField(max_length=200)),
                ('image_position', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], default='LEFT', max_length=10)),
                ('pages', models.ManyToManyField(related_name='banner_blocks', to='page.page')),
            ],
            options={
                'verbose_name': 'Banner Block',
                'verbose_name_plural': 'Banner Blocks',
            },
        ),
        migrations.CreateModel(
            name='ImagePageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('alt_text', models.CharField(max_length=200)),
                ('pages', models.ManyToManyField(related_name='page_header_images', to='page.page')),
            ],
            options={
                'verbose_name': 'Image Page Header',
                'verbose_name_plural': 'Image Page Headers',
            },
        ),
    ]
