# Generated by Django 5.1.4 on 2025-01-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_bannerblock_imagepageheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(upload_to='images', verbose_name='Imagen')),
                ('alt_text', models.CharField(max_length=200, verbose_name='Texto alternativo')),
                ('block_type', models.CharField(choices=[('BANNER', 'Banner'), ('IMAGE', 'Imagen')], default='BANNER', max_length=10, verbose_name='Tipo de bloque')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Bloque de Inicio',
                'verbose_name_plural': 'Bloques de Inicio',
                'ordering': ['order'],
            },
        ),
    ]
