# Generated by Django 5.1.4 on 2025-01-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_homeblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(upload_to='images', verbose_name='Imagen')),
                ('alt_text', models.CharField(max_length=200, verbose_name='Texto alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('pages', models.ManyToManyField(related_name='slider_blocks', to='page.page')),
            ],
            options={
                'verbose_name': 'Bloque de Slider',
                'verbose_name_plural': 'Bloques de Slider',
                'ordering': ['order'],
            },
        ),
    ]
