# Generated by Django 5.1.4 on 2025-01-17 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_sliderblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderblock',
            options={'verbose_name': 'Bloque de Slider', 'verbose_name_plural': 'Bloques de Slider'},
        ),
        migrations.RemoveField(
            model_name='sliderblock',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='sliderblock',
            name='content',
        ),
        migrations.RemoveField(
            model_name='sliderblock',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sliderblock',
            name='order',
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Imagen')),
                ('alt_text', models.CharField(max_length=200, verbose_name='Texto alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='page.sliderblock')),
            ],
            options={
                'verbose_name': 'Imagen de Slider',
                'verbose_name_plural': 'Imágenes de Slider',
                'ordering': ['order'],
            },
        ),
    ]
